### ISSUE TITLE
Failing simple Nix workflow for scheduled jobs

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#103]
As first reported by @chdoc, the simple Nix CI workflow currently implemented by the `nix-action.yml.mustache` template currently fails for scheduled (`cron`) jobs. The failures appeared after the changes in #100, and are very likely related. Basically, *all* Nix CI jobs fail with the same message:
```
invalid refspec '+refs/pull//head:refs/remotes/pull//head'
```
One example of a failing job can be found here: https://github.com/coq-community/reglang/actions/runs/1208112337

As a workaround, I [disabled](https://github.com/coq-community/reglang/commit/ec5d2aefa0081314bc55b8fc8f0f503d15af35c7) the Nix CI cronjob for reglang. Probably we should prohibit cronjobs directly in the template until this problem is solved. Or what do you recommend in the short term @Zimmi48?

**Comment by Zimmi48** [comment]
Indeed, I'm not surprised, because I forgot to test and account for this trigger. I'll look into it today to see if there's an easy fix or if we should temporarily remove the `schedule` trigger from the template.
