### ISSUE TITLE
Nix CI workflow failure on Coq master with old template

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#109]
In Huffman, the simple Nix CI workflow seems to consistently fail on Coq `master` for the last two days, for example: https://github.com/coq-community/huffman/runs/4090267105?check_suite_focus=true

Error message:
```
Error: Action failed with error: Error: The process '/usr/bin/sh' failed with exit code 1
(node:1975) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/sh' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:907:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:890:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/cachix/cachix-action/v8/dist/main/index.js:790:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:1975) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Not sure if this is related to changes in the Coq Nix Toolbox or not, so reporting here first @Zimmi48.

**Comment by Zimmi48** [comment]
I think the two lines above in the log are what matters:
```
/usr/bin/sh -c nix path-info --all | grep -v '.drv$' > /tmp/store-path-pre-build
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

They seem to indicate that the problem is that the version of Nix that is installed has been upgraded to 2.4 but the Cachix commands that are run are not expecting that. There have been updates to these Cachix actions recently: can you regenerate your workflow from the latest version of the templates to see if the failure still occurs?

In any case, this cannot be related to the Coq Nix Toolbox, because at this point, it hasn't been run.

**Comment by palmskog** [comment]
OK, it looks like rolling out the latest simple Nix CI templating makes the problem go away. I was confused since in a pull request, the "new" Nix CI and the "old" Nix CI are both run, and the only visible difference is the suffix after `pull_request_`.

But these observations also mean an old Nix simple workflow CI is completely broken, and must be updated everywhere. Now I get some use of the `nix-action` topic/tag at least, and then I'll close this issue when updates are done.

**Comment by palmskog** [comment]
Closing now since I believe I have updated all `nix-action.yml` in coq-community.

**Comment by Zimmi48** [comment]
Thanks! It's annoying that this update was required indeed.
