### ISSUE TITLE
documentation on meta.yml 

### ISSUE THREAD

**Issue by gmalecha** [coq-community/templates#19]
It would be nice if there was a template for the meta.yml (or a link to a template).

**Comment by Zimmi48** [comment]
I feel like we are in a loop: the original versions of the templates were informal. Then, we decided to use the mustache format. This leads to the introduction of `meta.yml`. But now `meta.yml` has become complex enough that a template (I guess an informal template) is requested... What about good documentation and a type schema instead? Cf. #24.

**Comment by gmalecha** [comment]
I think that a simple example would be sufficient for this. It could easily be linked from the README of this repository or included verbatim in it. As it is, the only way to understand what to put in there is to read all of the mustache files.

```yaml
longname: Example
shortname: Example # when would these be different?
authors:
  - # your name
```

If you want to get fancy (and I assume that you don't), you could write a simple cli that asks all the questions, but it seems unnecessary.

**Comment by Zimmi48** [comment]
OK, in fact we used to have concrete examples (based on existing projects) but it was hard to keep them in sync with the evolution of the templates, so they were removed (coq-community/manifesto#95) in favor of linking to example projects from the README. Maybe these example projects should be better highlighted, and maybe we should also provide a dummy `meta.yml` with comments like you did. I quite like this idea in fact, and I am ready to prepare the dummy example if @palmskog agrees.

**Comment by liyishuai** [comment]
We should provide a full reference of all the supported keys, like [Travis CI](https://config.travis-ci.com/), [CircleCI](https://circleci.com/docs/2.0/configuration-reference/), and [GitHub Actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions) do.
