### ISSUE TITLE
gitlab-ci template?

### ISSUE THREAD

**Issue by gmalecha** [coq-community/templates#25]
Does someone have a gitlab-ci template?

**Comment by erikmd** [comment]
Yes, see e.g.:

- https://gitlab.com/erikmd/docker-coq-gitlab-ci-demo-1 (standard version, without Dockerfile)
- https://gitlab.com/erikmd/docker-coq-gitlab-ci-demo-2 (version with a Dockerfile)

**Comment by Zimmi48** [comment]
Note that is this is for use with a GitHub repo, setting @coqbot to synchronize PRs should be useful (cf. README at https://github.com/coq/bot).

**Comment by Zimmi48** [comment]
Despite how good GitLab CI is, it seems to me that as long as coq-community's projects are on GitHub, we should favor CI solutions that integrate well with GitHub (we already provide GitHub Actions and Travis templates and might add a template for CircleCI, cf. #1).
