### ISSUE TITLE
Change all references to Gitter chat to Zulip chat

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#40]
Both the README and website templates reference the Gitter chat. This should be changed to references to the new Zulip chat, following the [change](https://github.com/coq/coq/commit/192d4bddea6df1b1ac9cad8354b0c821e1ba2534) to Coq's README.

**Comment by Zimmi48** [comment]
More specifically, the badge could link directly to the coq-community steam as was done in the Math-Comp README.

**Comment by Zimmi48** [comment]
- [ ] Update template (#43)
- [ ] Update repositories using the README template
- [ ] Update repositories not using the template:
  - [ ] Template repo
  - [ ] Manifesto repo
  - [ ] VSCoq repo

**Comment by palmskog** [comment]
There is another reference to the Gitter chat in the contribution guide in the manifesto repo.

**Comment by Zimmi48** [comment]
Good catch!

**Comment by Zimmi48** [comment]
coq-community/manifesto#105

**Comment by Zimmi48** [comment]
Last project updated, we can finally close this :tada:
