### ISSUE TITLE
Adding `default.nix`

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/templates#45]
Can someone add a `default.nix` file in order to be able to run `nix-shell --run ./generate.sh` directly?

**Comment by Zimmi48** [comment]
FTR, the only dependency to this script is a mustache tool, and `mustache-go` is the tool that I found available though Nix that is able to parse YAML. Writing the `default.nix` file should be pretty straightforward.

**Comment by CohenCyril** [comment]
Yes I noticed, but I did not have the time to test mustache-go and I do not know if it matches the requirements (only ``ruby-mustache`` was mentionned before now...)

**Comment by Zimmi48** [comment]
Is the command now documented in the `README` for Nix users enough to close this issue?

**Comment by CohenCyril** [comment]
I still think there should be a `shell.nix`

**Comment by CohenCyril** [comment]
I can submit a PR for that
