### ISSUE TITLE
Coq namespace should be optional in README.md template

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#53]
Currently, omitting `namespace` in `meta.yml` results in a nonsensical generated README.md which lists a line with an empty Coq namespace. We should make `namespace` optional, so the README.md template can be used in non-Coq projects, like proviola.

**Comment by anton-trunov** [comment]
Another option, I guess, would be to introduce a project type selector and not consider `namespace` for non-Coq projects. WDYT? Would it complicate things too much?

**Comment by palmskog** [comment]
Given that this was the only "non-optional" field for the README.md, having this kind of configurability seems a bit premature. I'm happy to revisit the decision further on when we have more non-Coq projects using the templates, though.

**Comment by anton-trunov** [comment]
Makes sense, thank you.
