### ISSUE TITLE
Allow build status in README.md for other branches than master

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#55]
Currently, build status is hardcoded to the `master` branch:
```
[travis-shield]: https://travis-ci.com/{{ organization }}/{{ shortname }}.svg?branch=master
...
[action-shield]: https://github.com/{{ organization }}/{{ shortname }}/workflows/CI/badge.svg?branch=master
```
This should be configurable through some parameter, e.g., `branch`, to let branches like `v8.12` get proper build status. This could also be used in the cloning instructions.

**Comment by lthms** [comment]
I am in need of this, tbh, and would happily propose a change to implement this if this is okay with you!

**Comment by palmskog** [comment]
A PR for this issue would be welcome.
