### ISSUE TITLE
allow specifying the Docker repo for 'tested_coq_opam_versions' for use in config.yml coq-action.yml

### ISSUE THREAD

**Issue by chdoc** [coq-community/templates#58]
PR #57 adds support for the `repo` variable, allowing to specify a Docker repo other than `coqorg/coq`. However, this feature cannot yet be used with `config.yml` and `coq-action.yml`. 

@erikmd , @palmskog I'm using neither Circle CI nor `coq-action`, so I would like to leave this to you.

**Comment by erikmd** [comment]
Thanks @chdoc, I'll have a look.

**Comment by erikmd** [comment]
I just opened https://github.com/coq-community/templates/pull/59 for the GitHub action
I'm not a Circle CI user though, so I'll let @liyishuai have a look if he can.

**Comment by palmskog** [comment]
This was handled by #59 and #61, so closing.
