### ISSUE TITLE
Gitlab mirror of this repo is stale

### ISSUE THREAD

**Issue by Blaisorblade** [coq-community/templates#68]
Nitpick, but https://gitlab.com/coq-community/templates says:

Pull mirroring failed 1 month ago.
Repository mirroring has been paused due to too many failed attempts, and can be resumed by a project maintainer.
Last successful update 1 month ago.

To wit:

![image](https://user-images.githubusercontent.com/289960/87228178-ac878380-c39f-11ea-96a2-e433fcbd3dbc.png)

**Comment by Zimmi48** [comment]
Thanks, this happens when someone force-pushes to the mirrored branches. I'll have a look now.
