### ISSUE TITLE
provide a curated shortlist of `meta.yml` files that serve as good starting points.

### ISSUE THREAD

**Issue by chdoc** [coq-community/templates#78]
One of the main hurdles for using templates is to come up with a `meta.yml` file. The `README.md` should list `meta.yml` files from a few well-chosen community projects covering various setups (plugins, pure libraries, one-branch, version-branches, dependencies, etc.)

Suggestions (will edit to follow discussion):

The `meta.yml` files of the following projects may serve a starting point. 
- [Huffman](https://github.com/coq-community/huffman) (pure library, no dependencies, coq-community) : [meta.yml](https://github.com/coq-community/huffman/blob/master/meta.yml)
- [AAC_tactics](https://github.com/coq-community/aac-tactics) (plugin, one-branch per Coq version): [meta.yml](https://github.com/coq-community/aac-tactics/blob/master/meta.yml).
- [reglang](https://github.com/coq-community/reglang) (pure library, mathcomp, custom docker images) : [meta.yml](https://github.com/coq-community/reglang/blob/master/meta.yml).
-  [StructTact](https://github.com/uwplse/StructTact) (pure library, no dependencies, no coq-community): [meta.yml](https://github.com/uwplse/StructTact/blob/master/meta.yml)

**Comment by palmskog** [comment]
I think we need projects that do not use the coq-community side of the templates as well, for example:
- [StructTact](https://github.com/uwplse/StructTact) (pure library, no dependencies, no coq-community): [meta.yml](https://github.com/uwplse/StructTact/blob/master/meta.yml)

**Comment by chdoc** [comment]
Hmm, I was about to add

- [Huffman](https://github.com/coq-community/huffman) (pure library, no dependencies, coq-community) : [meta.yml](https://github.com/coq-community/huffman/blob/master/meta.yml)

However, in the [meta.yml](https://github.com/coq-community/huffman/blob/master/meta.yml#L43) I find the wollowing:
```
tested_coq_nix_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master
```
Given that the project uses `actions`, which IIUC currently does not support Nix, this is a bit misleading.

**Comment by palmskog** [comment]
@chdoc the reason I keep Nix in `meta.yml` is in anticipation of Cyril's work on Action-based Nix CI. It's free to have there in the meantime.
