### ISSUE TITLE
Document that the Travis template is deprecated

### ISSUE THREAD

**Issue by palmskog** [coq-community/templates#79]
This is a reminder that we need to document that the Travis template is now deprecated, but will be retained for possible use by anyone who has a paying Travis account, etc.

**Comment by Zimmi48** [comment]
This was recently documented as "not for coq-community projects" in the README.

**Comment by Zimmi48** [comment]
Though we should also fix https://github.com/coq-community/manifesto/wiki/Recommended-Project-Structure

**Comment by anton-trunov** [comment]
> Though we should also fix https://github.com/coq-community/manifesto/wiki/Recommended-Project-Structure

I did a pass on this and tweak some more sections along the way.

**Comment by Zimmi48** [comment]
Great, thank you!

**Comment by anton-trunov** [comment]
Thanks for the reminder!
