### ISSUE TITLE
All generated file should mention they were generated

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/templates#84]
I suggest adding a header to each template, as a comment in the target language, to mention two things:
- that they are generated
- how to regenerate them
- that this is documented here on coq-community/templates.

Hence I suggest that the following gets added to all generated file assuming
1. `#` is the symbol for commenting in the target language of a given template
2. that `meta.yml` is the name of the meta data file
```
# This file was generated from `meta.yml`, please do not edit manually.
# Follow the instructions on https://github.com/coq-community/templates to regenerate.
```

In a second step, we could provide a generated file `./regenerate.sh` (with possible option `--nix`) in order to reperform the instructions from https://github.com/coq-community/templates without further arguments...

CC: @Zimmi48 @strub

**Comment by Zimmi48** [comment]
The header sounds like a good practice indeed.

I'm not convinced by the `regenerate.sh` script though. My point of view was rather than one could set up @coqbot to automatically open PRs when the templates are updated.

**Comment by CohenCyril** [comment]
> I'm not convinced by the `regenerate.sh` script though. My point of view was rather than one could set up @coqbot to automatically open PRs when the templates are updated.

this is not incompatible... the script coqbot runs could be available to users as well...

**Comment by Zimmi48** [comment]
For sure. I'm just not inclined to commit it everywhere.

**Comment by CohenCyril** [comment]
This could be an option of `meta.yml` ;)
